# Generated by Django 6.0.6 on 2026-06-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
