# Generated by Django 6.0.6 on 2026-06-30 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='favoritepokemon',
            name='pokemon_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pokemons.pokemon'),
        ),
    ]
